/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ems;

/**
 *
 * @author Subhro Ghosh
 */

import java.awt.Desktop;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.*;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GenResultPage extends javax.swing.JFrame
{

    /**
     * Creates new form GenResultPage
     */
    
    private ConnectionToDatabase cdb;
    private Connection conn;
    private DefaultTableModel modelStudents;
    
    private final String PATH = "S:\\Javaprogram\\NetBeans\\ExaminationManagementSystem\\html&css\\result";
    private final String OUTPUT_FILE_NAME = "generated-result.html";
    private final String INPUT_HEADER_FILE_NAME = "master-result-head.html";
    private final String INPUT_BODY_FILE_NAME = "master-result-body.html";
    
    
    public GenResultPage()
    {
        initComponents();
        
        cdb = new ConnectionToDatabase();
        
        try
        {
            conn = cdb.startConnection();
        } catch (SQLException ex)
        {
//            Logger.getLogger(UserSignUpPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Object cols[] = "Name,Gurdian Name,D.O.B,Roll No,Marks,Grade,Status".split(",");
        modelStudents = new DefaultTableModel(cols, 0);
        tableStudents.setModel(modelStudents);
        
        populateStudentTable();
        
        this.setVisible(true);
        
        File f = new File(PATH, OUTPUT_FILE_NAME);
        
        if(f.exists())
        {
            JOptionPane.showMessageDialog(this, "Result Already Generated!");
            btnGenerate.setEnabled(false);
            btnView.setEnabled(true);
        }
        else
        {
            btnGenerate.setEnabled(true);
            btnView.setEnabled(false);
        }
        
        
    }
    
    private void populateStudentTable()
    {
        ResultSet rs = getStudentDetails();
        try
        {
            while(rs.next())            
            {
                int marks = rs.getInt("Marks");
                Object ar[] = {rs.getString("Name"), rs.getString("Gurdian_Name"), rs.getDate("DOB").toString(),rs.getString("Roll_No"), marks,
                                    calculateGrade(marks), marks >= 30 ? "Passed" : "Failed"};
                
                modelStudents.addRow(ar);
                
            }
        } catch (Exception ex)
        {
            Logger.getLogger(GenAdmitPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStudents = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnGenerate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnCancle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Result Page");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3));

        tableStudents.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(tableStudents);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("List of Eligible Students");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 204, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addGap(289, 289, 289))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        btnGenerate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images&Icons/pencil.png"))); // NOI18N
        btnGenerate.setText("Generate");
        btnGenerate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGenerateActionPerformed(evt);
            }
        });

        btnView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images&Icons/view.png"))); // NOI18N
        btnView.setText("View");
        btnView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnView.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnViewActionPerformed(evt);
            }
        });

        btnCancle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images&Icons/close.png"))); // NOI18N
        btnCancle.setText("Cancel");
        btnCancle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancle.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(btnGenerate)
                        .addGap(18, 18, 18)
                        .addComponent(btnView)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancle)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnGenerate)
                    .addComponent(btnCancle))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGenerateActionPerformed
    {//GEN-HEADEREND:event_btnGenerateActionPerformed
        try
        {
            // TODO add your handling code here:
            genResult();
            JOptionPane.showMessageDialog(this, "Result Generated!");
            btnGenerate.setEnabled(false);
            btnView.setEnabled(true);

        } catch (FileNotFoundException ex)
        {
            Logger.getLogger(GenAdmitPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex)
        {
            Logger.getLogger(GenAdmitPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnViewActionPerformed
    {//GEN-HEADEREND:event_btnViewActionPerformed
        // TODO add your handling code here:
        if(!Desktop.isDesktopSupported())
        System.out.println("Desktop not supported");
        else
        {
            try
            {
                Desktop dtp = Desktop.getDesktop() ;

                dtp.open(new File(PATH, OUTPUT_FILE_NAME));
            } catch (IOException ex)
            {
                Logger.getLogger(GenAdmitPage.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_btnViewActionPerformed

    private void btnCancleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancleActionPerformed
    {//GEN-HEADEREND:event_btnCancleActionPerformed
        // TODO add your handling code here:
        cdb.closeConnection();
        this.setVisible(false);
        new AdminHomePage();
    }//GEN-LAST:event_btnCancleActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        // TODO add your handling code here:
        cdb.closeConnection();
        new AdminHomePage();
    }//GEN-LAST:event_formWindowClosing

    private void genResult() throws FileNotFoundException, SQLException
    {
        
        //Save the header
        StringBuilder sb = readHtmlFile(PATH+"\\"+INPUT_HEADER_FILE_NAME);
        PrintWriter pw = new PrintWriter(new File(PATH, OUTPUT_FILE_NAME));
        pw.println(sb.toString());
        
        //Save the body
        pw.println("<body>");
        String strMasterBody = readHtmlFile(PATH+"\\"+INPUT_BODY_FILE_NAME).toString();
        
        record NameValue(String name, String value){}
         NameValue ar[] = new NameValue[7];
         
         ResultSet rs = getStudentDetails();
         
         while(rs.next())
         {
            sb = new StringBuilder(strMasterBody);
            
            ar[0] = new NameValue("name",rs.getString("Name"));
            ar[1] = new NameValue("gname",rs.getString("Gurdian_Name"));
            ar[2] = new NameValue("dob",rs.getDate("DOB").toString());
            ar[3] = new NameValue("roll",rs.getString("Roll_No"));
            
            int marks = rs.getInt("Marks");
            
            ar[4] = new NameValue("marks",marks+"");
            ar[5] = new NameValue("grade",calculateGrade(marks));
            ar[6] = new NameValue("status", marks >= 30 ? "Passed" : "Failed");
            
            for (NameValue nv : ar)
            {
                replaceAll(sb, "%"+nv.name+"%", nv.value);
            }
            
            pw.println(sb.toString());
         }
        
        pw.println("</body>");
        pw.println("</html>");
        pw.close();
    }
    
    private StringBuilder readHtmlFile(String inputFileName) throws FileNotFoundException
    {
        StringBuilder sb = new StringBuilder();
        
        Scanner sc = new Scanner(new FileInputStream(inputFileName));
        while(sc.hasNextLine())
        {
            sb.append(sc.nextLine());
            sb.append("\n");
        }
        sc.close();
        return sb;
    }
    
    private void replaceAll(StringBuilder sb, String what, String with)
    {
        int p =0;
        while(true)
        {
            p = sb.indexOf(what,p);
            if(p<0)
                break;
            
            sb.replace(p, p+what.length(), with);
            p+= with.length();
        }
        
    }
    
    private ResultSet getStudentDetails()
    {
        String fetch = "SELECT Name, Gurdian_Name, DOB, Roll_no, Marks FROM Student  WHERE Attendance = \"P\" ";
        
        ResultSet rs = null;
        try
        {
            PreparedStatement psmt = conn.prepareStatement(fetch);
            
            rs = psmt.executeQuery();
            
        } catch (SQLException ex)
        {
            Logger.getLogger(GenAdmitPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return rs;
        
    }
    
    private String calculateGrade(int marks)
    {
        
        String grade = null;
        
        if(marks>=90)
            grade = "O";
        else if(marks >= 80)
            grade = "A+";
        else if(marks >= 70)
            grade = "A";
        else if(marks >= 60)
            grade = "B+";
        else if(marks >= 50)
            grade = "B";
        else if(marks >= 40)
            grade = "C";
        else if(marks >= 30)
            grade = "P";
        else
            grade = "F";
        
        return grade;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GenResultPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GenResultPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GenResultPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GenResultPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new GenResultPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancle;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableStudents;
    // End of variables declaration//GEN-END:variables
}
