USE EMS;

DELETE FROM ExamZone;
INSERT INTO ExamZone SET Name = 'Barasat';
INSERT INTO ExamZone SET Name = 'Madhyamgram';
INSERT INTO ExamZone SET Name = 'Barrackpore';
INSERT INTO ExamZone SET Name = 'Airport';
INSERT INTO ExamZone SET Name = 'Newtown';
INSERT INTO ExamZone SET Name = 'Bidhan Nagar';
INSERT INTO ExamZone SET Name = 'Tollygaunge';
INSERT INTO ExamZone SET Name = 'Kalighat';
INSERT INTO ExamZone SET Name = 'Maidan';
INSERT INTO ExamZone SET Name = 'Sealdah';
INSERT INTO ExamZone SET Name = 'Central';
INSERT INTO ExamZone SET Name = 'Shyambazar';
INSERT INTO ExamZone SET Name = 'Bagbazar';
INSERT INTO ExamZone SET Name = 'Belgachia';
INSERT INTO ExamZone SET Name = 'DumDum';
INSERT INTO ExamZone SET Name = 'Dakshineshwar';
INSERT INTO ExamZone SET Name = 'Khidirpur';
INSERT INTO ExamZone SET Name = 'Taratala';
INSERT INTO ExamZone SET Name = 'Behala';
INSERT INTO ExamZone SET Name = 'Joka';
INSERT INTO ExamZone SET Name = 'Jadavpur';

DELETE FROM ExamCenter;
INSERT INTO ExamCenter SET Name = "Adarsha Vidyapith", Address = "15/1C/H/8 Muraripukur Road, Manicktala - 700067", Zone_Id = 6, Center_No = "AV001";
INSERT INTO ExamCenter SET Name = "Kumar Asutosh Institution", Address = "6/1 Dum Dum Road, Sinthee - 700030", Zone_Id = 15, Center_No = "KHI002";
INSERT INTO ExamCenter SET Name = "North End Girls High School", Address = "6/1, Dum Dum Road, Sinthee - 700030", Zone_Id = 15, Center_No = "NGHS003";
INSERT INTO ExamCenter SET Name = "Shyambazar Vidyamandir", Address = "115/1 Bidhan Sarani, Shyambazar - 700004", Zone_Id = 12, Center_No = "SV004";
INSERT INTO ExamCenter SET Name = "Chowringhee High School", Address = "12 A Chowringhee Lane, New Market - 700016", Zone_Id = 9, Center_No = "CHS005";
INSERT INTO ExamCenter SET Name = "Jayaswal Vidyamandir for Girls", Address = "172 A Vivekananda Road, Maniktala - 700006", Zone_Id = 11, Center_No = "JVG006";
INSERT INTO ExamCenter SET Name = "Bowbazar Training High School", Address = "17 Dhiren Dhar Sarani, Bowbazar - 700012", Zone_Id = 11, Center_No = "BTHS007";
INSERT INTO ExamCenter SET Name = "St Micheael's Academy", Address = "2B Chitranjan Avenue, Princep Street - 700072", Zone_Id = 9, Center_No = "SMA008";
INSERT INTO ExamCenter SET Name = "A.K. Ghosh Memorial High School", Address = "164/A/6, Prince Anwar Shah Road, Lake Gardens - 700045", Zone_Id = 7, Center_No = "AKGM009";
INSERT INTO ExamCenter SET Name = "Bani Bhaban High School", Address = "Sree Colony, Netajinagar - 700092", Zone_Id = 7, Center_No = "BBHS010";
INSERT INTO ExamCenter SET Name = "Kasba Chittaranjan High School", Address = "80 R K Ghosal Road, Kasba - 700042", Zone_Id = 21, Center_No = "KCHS011";
INSERT INTO ExamCenter SET Name = "Jadavpur Bagha Jatin Balika Vidyalaya", Address = "Baghajatin Palli, Nrtajinagar - 700092", Zone_Id = 21, Center_No = "JBBV012";
INSERT INTO ExamCenter SET Name = "Sarat Chandra Pal Girls High School", Address = "43A Ramkamal Street, Kidderpore - 700023", Zone_Id = 17, Center_No = "SCHS013";
INSERT INTO ExamCenter SET Name = "Tollygaunge Bangur High School", Address = "34 Golf Club Road, Golf Green - 700033", Zone_Id = 7, Center_No = "TBHS014";
INSERT INTO ExamCenter SET Name = "R D Memorial School", Address = "25/11/A K.P.Roy Lane, Dhakuria - 700031", Zone_Id = 21, Center_No = "RDMS015";
INSERT INTO ExamCenter SET Name = "Alipore Girls' & Boys' High School", Address = "10, Balaka Complex,Thakurpukur - 700104", Zone_Id = 20, Center_No = "AHS016";
INSERT INTO ExamCenter SET Name = "Behala Aryya Vidyamandir", Address = "173, Unique Park Rd, Behala - 700034", Zone_Id = 19, Center_No = "BAV017";
INSERT INTO ExamCenter SET Name = "Barasat Indira Gandhi Memorial High School", Address = "18, Jessore Rd, Rathtala, Barasat - 700124", Zone_Id = 1, Center_No = "BIGS018";
INSERT INTO ExamCenter SET Name = "Bethune Collegiate School", Address = "Bidhan Sarani Rd, Hedua - 700006", Zone_Id = 11, Center_No = "BCS019";
INSERT INTO ExamCenter SET Name = "Dum Dum Kishore Bharati High School", Address = "P 2/A, Motijheel Ave, Dum Dum - 700074", Zone_Id = 15, Center_No = "DKBS020";
